### ISSUE TITLE
.tern-project

### ISSUE THREAD

**Issue by tla-dev** [vim-dist/webvim#41]
I just did a fresh install from master and I have the following error when opening a javascript file:

RuntimeError: Warning: Unable to detect a .tern-project file in the hierarchy before /home/USER/git/myproject and no global .tern-config file was found. This is required for accurate JavaScript completion.
 Please see the User Guide for details.

**Comment by krampstudio** [comment]
Thanks for reporting. 

This bug is linked to #6

Please add a [.tern-project](https://gist.github.com/krampstudio/efc8935a4dea6285cbac9f1be5707526) file into `$HOME`or at the root of your project. It will fix the problem while I update webvim.

Sorry for the inconvenience, next time I'll push the developments into another branch before the release.

**Comment by tla-dev** [comment]
I'm happy to be tester! Thanks for you work.
